# Generated by Django 5.0.5 on 2024-07-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_kakao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
