version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    image: app:django
    container_name: delight-spot
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      delight-spot-database:
        condition: service_healthy
    networks:
      - my-network

  delight-spot-database:
    image: postgres:13
    container_name: delight-spot-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: delight-spot-db
      POSTGRES_USER: jth
      POSTGRES_PASSWORD: jth
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jth"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:


#   delight-spot-database:
#     image: mysql:8.0
#     platform: linux/amd64
#     container_name: delight-spot-container
#     volumes:
#       - ./data/mysql/db:/var/lib/mysql
#       # - mysql-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: jth
#       MYSQL_DATABASE: delight-spot-db
#       MYSQL_USER: jth
#       MYSQL_PASSWORD: jth
#     ports:
#       - "3306:3306"
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p", "jth"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     networks:
#       - my-network

# volumes:
#   mysql-data:

# networks:
#   my-network:


