# Generated by Django 5.0.5 on 2024-06-29 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_initial'),
        ('reviews', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.URLField()),
                ('reviews', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_photos', to='reviews.reviews')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
