# Generated by Django 5.0.5 on 2024-07-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
