# Generated by Django 5.0.5 on 2024-07-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviews_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_photo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
