# Generated by Django 5.0.5 on 2024-07-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviews_review_photo'),
        ('stores', '0006_alter_store_store_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store'),
        ),
    ]
