# Generated by Django 5.0.5 on 2024-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='store',
            field=models.ManyToManyField(blank=True, default='', related_name='bookings', to='stores.store'),
        ),
    ]
