# Generated by Django 5.0.5 on 2024-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Selling List',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('kind_menu', models.CharField(choices=[('food', '음식'), ('cafe', '카페'), ('ect', '기타')], max_length=20)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Store',
            },
        ),
    ]
