# Generated by Django 5.0.5 on 2024-07-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_store_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_photo',
            field=models.JSONField(blank=True),
        ),
    ]
